apiVersion: v1
kind: ServiceAccount
metadata:
  name: users
  namespace: patricia-app
  {{- if .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
  {{- end }}
